spring:
  application:
    name: haole-rocketmq-spring-sample

  datasource:
    name: hikari
    url: jdbc:mysql://127.0.0.1:3306/yiibaidb?useUnicode=true&amp;characterEncoding=utf-8&amp;useOldAliasMetadataBehavior=true
    username: ddl_user
    password: sjzsjz
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver   #com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

server:
  port: 10600

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.haole.rocketmq.model
  config-location: classpath:mybatis-config.xml